Repository BuildForSDG/Team-220-Frontend, pull requests merged in 2020-05, with the labels that each got.

#4 [chore] Install Angular Framework
  .editorconfig
  .gitignore
  angular.json
  browserslist
  e2e/protractor.conf.js
  e2e/src/app.e2e-spec.ts
  e2e/src/app.po.ts
  e2e/tsconfig.json
  karma.conf.js
  ngsw-config.json
  package-lock.json
  package.json
  src/_redirects
  src/app/app-routing.module.ts
  src/app/app.component.css
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/assets/.gitkeep
  src/assets/icons/icon-128x128.png
  src/assets/icons/icon-144x144.png
  src/assets/icons/icon-152x152.png
  src/assets/icons/icon-192x192.png
  src/assets/icons/icon-384x384.png
  src/assets/icons/icon-512x512.png
  src/assets/icons/icon-72x72.png
  src/assets/icons/icon-96x96.png
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/favicon.ico
  src/index.html
  src/main.ts
  src/manifest.webmanifest
  src/polyfills.ts
  src/robots.txt
  src/sitemap.xml
  src/styles.css
  src/test.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.spec.json
  tslint.json
  yarn.lock
Labels: help wanted

#5 feat: Add linting, code formatting and testing setup to the repo
  .eslintrc.js
  .vscode/settings.json
  babel.config.js
  jest.config.js
  karma.conf.js
  package-lock.json
  package.json
  src/_redirects
Labels: enhancement, help wanted

#11 feat : build app logo
  src/assets/icons/icon-128x128.png
  src/assets/icons/icon-144x144.png
  src/assets/icons/icon-152x152.png
  src/assets/icons/icon-192x192.png
  src/assets/icons/icon-384x384.png
  src/assets/icons/icon-512x512.png
  src/assets/icons/icon-72x72.png
  src/assets/icons/icon-96x96.png
  src/favicon.ico
Labels: enhancement, good first issue
